// examples/framework-matrix/fixtures/vue/app.vue
<script setup>
// Vue 3 single-file component implementing the shared matrix UI contract. Uses v-model
// (two-way binding) on the input, so it is a controlled field backed by reactive state
// — driving it with real keystrokes proves the tools work through Vue's reactivity.
import { ref } from 'vue'

const name = ref('')
const status = ref('No greeting yet')

function greet() {
  const who = name.value.trim() || 'stranger'
  status.value = `Hello, ${who}!`
  console.log(`greeted ${who}`)
}
</script>

<template>
  <main>
    <h1>Vue fixture</h1>
    <label>Your name <input id="name" aria-label="Your name" v-model="name" /></label>
    <button id="greet" type="button" @click="greet">Greet</button>
    <p id="status">{{ status }}</p>
  </main>
</template>

// examples/framework-matrix/fixtures/react/app.jsx
// React implementation of the shared matrix UI contract: a "Your name" input, a
// "Greet" button, and a #status line. Deliberately uses a CONTROLLED input (value +
// onChange) and React's synthetic onClick, so driving it proves the tools work through
// React's virtual DOM and event system — not just against static markup. Bundled to a
// self-contained IIFE by build-fixtures.mjs (esbuild), loaded by index.html.
import { useState } from 'react'
import { createRoot } from 'react-dom/client'

function App() {
  const [name, setName] = useState('')
  const [status, setStatus] = useState('No greeting yet')

  const greet = () => {
    const who = name.trim() || 'stranger'
    setStatus(`Hello, ${who}!`)
    console.log(`greeted ${who}`)
  }

  return (
    <main>
      <h1>React fixture</h1>
      <label>
        Your name
        <input
          id="name"
          type="text"
          aria-label="Your name"
          value={name}
          onChange={(e) => setName(e.target.value)}
        />
      </label>
      <button id="greet" type="button" onClick={greet}>
        Greet
      </button>
      <p id="status">{status}</p>
    </main>
  )
}

const root = document.getElementById('root')
if (root) createRoot(root).render(<App />)
